# 'bundle exec jekyll serve' to test
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: laila c. johnston
email: lailacjohnston@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    laila c. johnston
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lailacj.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
socials:
    twitter: lailacjohnston
    linkedin: lailacjohnston
    #instagram: swubear
    #last-fm: sarahwu_

collections:
    publications:
        output: true
        permalink: /:collection/:name

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
